vault_secret: secret/ansible/secret-pass/data/postgres_user_creds
database_arr: "{{ lookup('hashi_vault', 'secret={{ vault_secret }} token={{ vault_token }} url={{ vault_url }} validate_certs=False') }}"
